### PR TITLE
bypass native addon when possible

### PR DESCRIPTION
**Pull request by bengl**
Via redefining through descriptors.

If unneeded, the binding is still built at install time, but at least it's no longer needed at runtime.

### CODE REVIEW

**Comment by TooTallNate** [comment]
Very cool! Which version of V8 (and Node) did this change happen? Is it part of ECMA?

**Comment by bengl** [comment]
It's [specced in ES6](http://www.ecma-international.org/ecma-262/6.0/#sec-function-instances-name). According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name#Browser_compatibility), function name configurability has been around since Chrome 43, so [V8 4.3](https://en.wikipedia.org/wiki/Google_Chrome_version_history). That means [nodejs/iojs 3.0.0](https://nodejs.org/en/download/releases/). This every Node release that's currently supported by the core team supports configurable function names, so if you're willing to drop support for no-longer-supported versions of node, I can also go ahead and remove the native fallback in this PR :smile: .

Further reference:

http://node.green/#ES2015-built-in-extensions-function--name--property-isn-t-writable--is-configurable

http://kangax.github.io/compat-table/es6/#test-function_name_property_isn't_writable,_is_configurable

**Comment by TooTallNate** [comment]
I'd be down for removing the native bindings, specifying `"node": ">= 3.0.0"` in the engines field so that npm gives a proper warning, and a note in the README to use `function-name@1` for older versions of Node 👍

**Comment by bengl** [comment]
Cool, did that.

**Comment by TooTallNate** [comment]
Haha, the Travis build is pretty cool. Exactly as you predicted it would be played out: https://travis-ci.org/TooTallNate/node-function-name/builds/215030026

**Comment by TooTallNate** [comment]
Awesome stuff @bengl! Merged.

**Comment by TooTallNate** [comment]
Published as new major version bump: https://github.com/TooTallNate/node-function-name/releases/tag/2.0.0

**Pull request merged**
